### ISSUE TITLE
`S3-Ferry` as a generic service to transfer files to and from any S3 platform

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/S3-Ferry#1]
AS AN Architect
I WANT TO use a generic service to trasnfer files to and from any S3 platform
SO THAT there wouldn't be any duplicated functionalities doing the same thing

### Acceptance Criteria

- [ ] S3 file transfers are triggered by an appropriate REST service
- [ ] All REST services are defined as DSL files in `YAML` format
> See [Ruuter](https://github.com/buerokratt/Buerokratt-DSL/tree/dev/Ruuter), [Resql](https://github.com/buerokratt/Buerokratt-DSL/tree/dev/Resql) and [DataMapper](https://github.com/buerokratt/Buerokratt-DSL/tree/dev/DataMapper/v2/backoffice/hbs) as reference
- [ ] REST calls may not pass directory paths
- [ ] REST calls may pass file names

#### Documentation

- [ ] Full documentation as `Readme.md` to cover all technical functionalities
- [ ] Create OpenAPI spec for all functionalities automatically

#### Technical requirements

- [ ] Based on the concept of [Amazon S3](https://en.wikipedia.org/wiki/Amazon_S3)
- [ ] Based on [Node.js](https://nodejs.org/en)
- [ ] When creating REST services, follow the concept of [RESTful Naming Convention](https://restfulapi.net/resource-naming)
- [ ] All secrets and variables are configurable from one file used as a single source of truth
- [ ] Deploy as a separate Docker instance on any environment
- [ ] Deploy on any Kubernetes environment
- [ ] End-to-end tests based on GitHub Actions

#### Functionalities

- [ ] REST service to list all files within defined source
- [ ] Transfer files from a defined source to a defined destination
- [ ] Apply service provider-specific DSLs to convert Ferry's own generic REST calls to service provider-specific ones
> The goal of this one is to gain service provider-independence by just creating service provider-specific data mapping files so that all of them understand S3-Ferry

> Similar approach is the core concept of the [Data Mapper](https://github.com/buerokratt/Buerokratt-DSL/tree/dev/DataMapper/v2/backoffice/hbs), but let's not make it a requirement when using S3-Ferry
